HIP_PATH ?= /opt/rocm/hip
HIPCC = $(HIP_PATH)/bin/hipcc
OPTS = -O3

# these are needed for m5ops
# Assumes gem5 and gem5-resources share a common parent directory.
GEM5_ROOT ?= ../../../../../gap-gem5
CFLAGS += -I$(GEM5_ROOT)/include -I/../graph_parser -I$(GEM5_ROOT)
LDFLAGS += -L$(GEM5_ROOT)/util/m5/build/x86/out -lm5

BASEEXE = pagerank
VARIANT ?= DEFAULT
ifeq ($(VARIANT),DEFAULT)
    EXECUTABLE = $(BASEEXE).gpufs
    CPPFILES += pagerank.cpp
else ifeq ($(VARIANT),SPMV)
    EXECUTABLE = $(BASEEXE)_spmv.gpufs
    CPPFILES += pagerank_spmv.cpp
endif

BIN_DIR ?= ./bin

all: $(BIN_DIR)/$(EXECUTABLE)

$(BIN_DIR)/$(EXECUTABLE): $(CPPFILES) ../graph_parser/parse.cpp ../graph_parser/util.cpp $(BIN_DIR)
	$(HIPCC) $(OPTS) --amdgpu-target=gfx900,gfx902 $(CXXFLAGS) ../graph_parser/parse.cpp ../graph_parser/util.cpp $(CPPFILES) -DGEM5_FS -o $(BIN_DIR)/$(EXECUTABLE) $(CFLAGS) $(LDFLAGS)

$(BIN_DIR):
	mkdir -p $(BIN_DIR)

clean:
	rm -rf $(BIN_DIR)

.PHONY: pagerank clean
