HIP_PATH ?= /opt/rocm
HIPCC = $(HIP_PATH)/bin/hipcc

DEF_EXE = pagerank_default.default
SPMV_EXE = pagerank_spmv.default

DEF_CPP = pagerank.cpp
SPMV_CPP = pagerank_spmv.cpp

OPTS = -O3 -Wno-unused-result
GCC_OPTS=--gcc-install-dir=/usr/lib/gcc/x86_64-linux-gnu/13
BIN_DIR ?= ./bin.default

all: $(BIN_DIR)/$(DEF_EXE) $(BIN_DIR)/$(SPMV_EXE)

$(BIN_DIR)/$(DEF_EXE): $(DEF_CPP) ../graph_parser/parse.cpp ../graph_parser/util.cpp $(BIN_DIR)
	# There is a futex issue in hipcc with the graph parser. Compile without opts until this is fixed.
	$(HIPCC) $(GCC_OPTS) -O0 --offload-arch=gfx900,gfx90a,gfx906,gfx942 $(CXXFLAGS) ../graph_parser/parse.cpp -o $(BIN_DIR)/parse.o -c
	$(HIPCC) $(GCC_OPTS) -O0 --offload-arch=gfx900,gfx90a,gfx906,gfx942 $(CXXFLAGS) ../graph_parser/util.cpp -o $(BIN_DIR)/util.o -c
	$(HIPCC) $(GCC_OPTS) $(OPTS) --offload-arch=gfx900,gfx90a,gfx906,gfx942 $(CXXFLAGS) $(BIN_DIR)/parse.o $(BIN_DIR)/util.o $(DEF_CPP) -o $(BIN_DIR)/$(DEF_EXE)

$(BIN_DIR)/$(SPMV_EXE): $(SPMV_CPP) ../graph_parser/parse.cpp ../graph_parser/util.cpp $(BIN_DIR)
	# There is a futex issue in hipcc with the graph parser. Compile without opts until this is fixed.
	$(HIPCC) $(GCC_OPTS) -O0 --offload-arch=gfx900,gfx90a,gfx906,gfx942 $(CXXFLAGS) ../graph_parser/parse.cpp -o $(BIN_DIR)/parse.o -c
	$(HIPCC) $(GCC_OPTS) -O0 --offload-arch=gfx900,gfx90a,gfx906,gfx942 $(CXXFLAGS) ../graph_parser/util.cpp -o $(BIN_DIR)/util.o -c
	$(HIPCC) $(GCC_OPTS) $(OPTS) --offload-arch=gfx900,gfx90a,gfx906,gfx942 $(CXXFLAGS) $(BIN_DIR)/parse.o $(BIN_DIR)/util.o $(SPMV_CPP) -o $(BIN_DIR)/$(SPMV_EXE)

$(BIN_DIR):
	mkdir -p $(BIN_DIR)

clean:
	rm -rf $(BIN_DIR)

.PHONY: pagerank clean
