HIP_PATH?= /opt/rocm
HIPCC=$(HIP_PATH)/bin/hipcc

EXECUTABLE = square.default
CPPSRC = square.cpp

OPTS = -O3 -Wno-unused-result --gcc-install-dir=/usr/lib/gcc/x86_64-linux-gnu/13 
BIN_DIR?= ./bin.default

square: $(BIN_DIR)/$(EXECUTABLE)

$(BIN_DIR)/$(EXECUTABLE): $(CPPSRC) $(BIN_DIR)
	$(HIPCC) $(OPTS) --offload-arch=gfx906 $(CXXFLAGS) $(CPPSRC) -o $(BIN_DIR)/$(EXECUTABLE)

$(BIN_DIR):
	mkdir -p $(BIN_DIR)

clean:
	rm -f $(BIN_DIR)/$(EXECUTABLE)
	rmdir --ignore-fail-on-non-empty $(BIN_DIR)

.PHONY: square clean
